# A03 - Factores cualitativos
## Juan Pedro Ley Valdez

In [ ]:
import pandas as pd

PARTE 1

In [ ]:
df = pd.read_csv("/datos_feo_bien.csv")
df['es_kahlua'] = (df['sabor'] == 'Kahlúa').astype(int)
df['es_horchata'] = (df['sabor'] == 'horchata').astype(int)
df['tamaño'] = df['tamaño'].map({'chica': 0, 'grande': 1})
df['hielo'] = df['hielo'].map({'sin': 0, 'con': 1})
df.head()

   tamaño  hielo     sabor  score  es_kahlua  es_horchata
0       1      0    Kahlúa    8.2          1            0
1       1      1    Kahlúa    9.0          1            0
2       0      0    Kahlúa    7.0          1            0
3       0      1    Kahlúa    7.5          1            0
4       1      1  horchata   10.0          0            1

In [ ]:
import statsmodels.api as sm


X = df.drop("score", axis=1)
X = X.drop("sabor", axis=1)


y = df["score"]

# Add a constant to the independent variables (X) for the OLS model
X = sm.add_constant(X)

model = sm.OLS(y, X)
results = model.fit()

print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.837
Model:                            OLS   Adj. R-squared:                  0.714
Method:                 Least Squares   F-statistic:                     6.824
Date:                Mon, 09 Feb 2026   Prob (F-statistic):             0.0473
Time:                        23:48:54   Log-Likelihood:                -6.6425
No. Observations:                   8   AIC:                             21.29
Df Residuals:                       4   BIC:                             21.60
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           4.3000      0.320     13.417      0.000       3.410       5.190
tamaño          2.4500      0.555      4.414      0.012       0.909       3.991
hielo           0.5500      0.555      0.991      0.378      -0.991       2.091
es_kahlua       2.1250      0.320      6.631      0.003       1.235       3.015
es_horchata     2.1750      0.320      6.787      0.002       1.285       3.065
==============================================================================
Omnibus:                        7.172   Durbin-Watson:                   1.431
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                1.242
Skew:                          -0.048   Prob(JB):                        0.537
Kurtosis:                       1.072   Cond. No.                     2.22e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.37e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

PARTE 2

In [ ]:
df = pd.read_csv("/datos_feo_bien.csv")
df['es_kahlua'] = (df['sabor'] == 'Kahlúa').astype(int)
df['es_horchata'] = (df['sabor'] == 'horchata').astype(int)
df['tamaño'] = df['tamaño'].map({'chica': 1, 'grande': -1})
df['hielo'] = df['hielo'].map({'sin': -1, 'con': 1})
df

   tamaño  hielo     sabor  score  es_kahlua  es_horchata
0      -1     -1    Kahlúa    8.2          1            0
1      -1      1    Kahlúa    9.0          1            0
2       1     -1    Kahlúa    7.0          1            0
3       1      1    Kahlúa    7.5          1            0
4      -1      1  horchata   10.0          0            1
5       1     -1  horchata    6.0          0            1
6       1      1  horchata    6.4          0            1
7      -1     -1  horchata    9.5          0            1

In [ ]:
X = df.drop("score", axis=1)
X = X.drop("sabor", axis=1)


y = df["score"]

# Add a constant to the independent variables (X) for the OLS model
X = sm.add_constant(X)

model = sm.OLS(y, X)
results = model.fit()

##print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  score   R-squared:                       0.837
Model:                            OLS   Adj. R-squared:                  0.714
Method:                 Least Squares   F-statistic:                     6.824
Date:                Mon, 09 Feb 2026   Prob (F-statistic):             0.0473
Time:                        23:51:47   Log-Likelihood:                -6.6425
No. Observations:                   8   AIC:                             21.29
Df Residuals:                       4   BIC:                             21.60
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           5.3000      0.185     28.644      0.000       4.786       5.814
tamaño         -1.2250      0.278     -4.414      0.012      -1.996      -0.454
hielo           0.2750      0.278      0.991      0.378      -0.496       1.046
es_kahlua       2.6250      0.293      8.973      0.001       1.813       3.437
es_horchata     2.6750      0.293      9.143      0.001       1.863       3.487
==============================================================================
Omnibus:                        7.172   Durbin-Watson:                   1.431
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                1.242
Skew:                          -0.048   Prob(JB):                        0.537
Kurtosis:                       1.072   Cond. No.                     1.84e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.54e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

### Conclusiones

Al cambiar el enconding para las variables de hielo y tamaño de 0 y 1, a -1 y 1, subió el intercepto del modelo por exactamente 1 punto. Esto es debido a que el intercepto representa el valor predicho cuando todas las variables explicativas son 0. En el modelo 1 se calcula el caso base, de bebida sin hielo y chica. En el modelo 2 se calcula el caso promedio por que el cero seria la mitad entre -1 y 1, y como las características extra de hielo y tamaño añaden valor, el promedio sube.